import { db } from '@/lib/db';
import { getSEOSettings, getSiteUrl, getI18nSettings } from '@/lib/system-settings';
import { locales, Locale, defaultLocale, getLocalePath } from '@/lib/i18n';

/**
 * llms.txt: 为 AI 爬虫和 LLM 提供结构化的 Markdown 网站概览
 * 遵循 https://llmstxt.org/ 规范
 */
export async function GET() {
    try {
        const seo = await getSEOSettings();
        const baseUrl = await getSiteUrl();
        const i18nSettings = await getI18nSettings();
        const enableMultiLanguage = i18nSettings?.enableMultiLanguage;

        // 基础信息
        let content = `# ${seo.siteName}\n\n`;
        content += `> ${seo.siteDescription}\n\n`;

        // 如果开启多语言，增加语言版本说明
        if (enableMultiLanguage) {
            content += `## Languages\n\n`;
            locales.forEach(locale => {
                const name = locale === 'zh' ? '简体中文' : 'English';
                const url = `${baseUrl}${getLocalePath('/', locale)}`;
                content += `- [${name}](${url})\n`;
            });
            content += `\n`;
        }

        // 核心页面
        content += `## Core Pages\n\n`;

        // 获取主要页面
        const pages = await db.page.findMany({
            where: { status: 'PUBLISHED' },
            select: { title: true, slug: true, lang: true },
            orderBy: [{ isDefault: 'desc' }, { updatedAt: 'desc' }],
            take: 20
        });

        pages.forEach(page => {
            const url = `${baseUrl}${getLocalePath(`/${page.slug}`, page.lang as any)}`;
            content += `- [${page.title}](${url}) (${page.lang})\n`;
        });

        // 最新文章
        const articles = await db.article.findMany({
            where: { status: 'PUBLISHED' },
            select: { title: true, slug: true, lang: true, summary: true },
            orderBy: { createdAt: 'desc' },
            take: 50
        });

        if (articles.length > 0) {
            content += `\n## Recent Articles\n\n`;
            articles.forEach(article => {
                const url = `${baseUrl}${getLocalePath(`/articles/${article.slug}`, article.lang as any)}`;
                content += `- [${article.title}](${url}): ${article.summary || ''} (${article.lang})\n`;
            });
        }

        // 最新产品
        const products = await db.product.findMany({
            where: { status: 'PUBLISHED' },
            select: { name: true, slug: true, lang: true, description: true },
            orderBy: { createdAt: 'desc' },
            take: 50
        });

        if (products.length > 0) {
            content += `\n## Products\n\n`;
            products.forEach(product => {
                const url = `${baseUrl}${getLocalePath(`/product/${product.slug}`, product.lang as any)}`;
                content += `- [${product.name}](${url}): ${product.description || ''} (${product.lang})\n`;
            });
        }

        // 引导至全量 Sitemap
        content += `\n## Resources\n\n`;
        content += `- [Full Sitemap](${baseUrl}/sitemap.xml): Complete index of all URLs for deep crawling.\n`;

        content += `\n---\n*Generated by GeoCMS for AI Interoperability. Last updated: ${new Date().toISOString().split('T')[0]}.*`;

        return new Response(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=600',
            },
        });
    } catch (error) {
        console.error('Error generating llms.txt:', error);
        return new Response('Error generating llms.txt', { status: 500 });
    }
}
