import { db } from '@/lib/db';
import { getSEOSettings, getSiteUrl } from '@/lib/system-settings';
import { locales, defaultLocale, getLocalePath } from '@/lib/i18n';

/**
 * llms.txt: 为 AI 爬虫和 LLM 提供结构化的 Markdown 网站概览
 * 遵循 https://llmstxt.org/ 规范
 */
export async function GET() {
    try {
        const seo = await getSEOSettings();
        const baseUrl = await getSiteUrl();

        // 基础信息
        let content = `# ${seo.siteName}\n\n`;
        content += `> ${seo.siteDescription}\n\n`;

        // 核心页面
        content += `## Core Pages\n\n`;

        // 获取主要页面
        const pages = await db.page.findMany({
            where: { status: 'PUBLISHED' },
            select: { title: true, slug: true, lang: true },
            orderBy: { updatedAt: 'desc' },
            take: 10
        });

        pages.forEach(page => {
            const url = `${baseUrl}${getLocalePath(`/${page.slug}`, page.lang as any)}`;
            content += `- [${page.title}](${url})\n`;
        });

        // 最新文章
        const articles = await db.article.findMany({
            where: { status: 'PUBLISHED' },
            select: { title: true, slug: true, lang: true, summary: true },
            orderBy: { createdAt: 'desc' },
            take: 10
        });

        if (articles.length > 0) {
            content += `\n## Recent Articles\n\n`;
            articles.forEach(article => {
                const url = `${baseUrl}${getLocalePath(`/articles/${article.slug}`, article.lang as any)}`;
                content += `- [${article.title}](${url}): ${article.summary || ''}\n`;
            });
        }

        // 最新产品
        const products = await db.product.findMany({
            where: { status: 'PUBLISHED' },
            select: { name: true, slug: true, lang: true, description: true },
            orderBy: { createdAt: 'desc' },
            take: 10
        });

        if (products.length > 0) {
            content += `\n## Products\n\n`;
            products.forEach(product => {
                const url = `${baseUrl}${getLocalePath(`/product/${product.slug}`, product.lang as any)}`;
                content += `- [${product.name}](${url}): ${product.description || ''}\n`;
            });
        }

        content += `\n---\n*Generated by GeoCMS for AI Interoperability.*`;

        return new Response(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=600',
            },
        });
    } catch (error) {
        return new Response('Error generating llms.txt', { status: 500 });
    }
}
