import { db } from '@/lib/db';
import { getSEOSettings, getSiteUrl, getI18nSettings } from '@/lib/system-settings';
import { locales, defaultLocale, getLocalePath } from '@/lib/i18n';

function stripHtml(html: string | null | undefined): string {
    if (!html) return '';
    return html.replace(/<[^>]*>?/gm, '').trim();
}

/**
 * llms-full.txt: 为 AI 提供全量、深度结构化的 Markdown 网站索引
 * 包含更多的文章、产品和页面明细，方便 LLM 进行全量上下文索引
 */
export async function GET() {
    try {
        const seo = await getSEOSettings();
        const baseUrl = await getSiteUrl();
        const i18nSettings = await getI18nSettings();
        const enableMultiLanguage = i18nSettings?.enableMultiLanguage;

        // 基础信息
        let content = `# Full Site Index - ${seo.siteName}\n\n`;
        content += `> ${seo.siteDescription}\n\n`;
        content += `This file contains a comprehensive list of all public content on ${seo.siteName} for deep indexing by AI models.\n\n`;

        // 如果开启多语言，增加语言版本说明
        if (enableMultiLanguage) {
            content += `## Languages\n\n`;
            locales.forEach(locale => {
                const name = locale === 'zh' ? '简体中文' : 'English';
                const url = `${baseUrl}${getLocalePath('/', locale)}`;
                content += `- [${name}](${url})\n`;
            });
            content += `\n`;
        }

        // 1. 全部核心页面
        content += `## Core Pages\n\n`;
        const pages = await db.page.findMany({
            where: {
                status: 'PUBLISHED',
                ...(enableMultiLanguage ? {} : { lang: defaultLocale })
            },
            select: { title: true, slug: true, lang: true },
            orderBy: [{ isDefault: 'desc' }, { updatedAt: 'desc' }]
        });

        pages.forEach(page => {
            const url = `${baseUrl}${getLocalePath(`/${page.slug}`, page.lang as any)}`;
            content += `- [${page.title}](${url}) (${page.lang})\n`;
        });

        // 2. 全量/大量文章
        content += `\n## Full Article Index\n\n`;
        const articles = await db.article.findMany({
            where: {
                status: 'PUBLISHED',
                ...(enableMultiLanguage ? {} : { lang: defaultLocale })
            },
            select: { title: true, slug: true, lang: true, summary: true, createdAt: true },
            orderBy: { createdAt: 'desc' },
            take: 1000 // 获取更多文章
        });

        if (articles.length > 0) {
            articles.forEach(article => {
                const url = `${baseUrl}${getLocalePath(`/articles/${article.slug}`, article.lang as any)}`;
                const date = new Date(article.createdAt).toISOString().split('T')[0];
                content += `- [${article.title}](${url}) [${date}]: ${stripHtml(article.summary)} (${article.lang})\n`;
            });
        }

        // 3. 全量产品
        const products = await db.product.findMany({
            where: {
                status: 'PUBLISHED',
                ...(enableMultiLanguage ? {} : { lang: defaultLocale })
            },
            select: { name: true, slug: true, lang: true, description: true },
            orderBy: { createdAt: 'desc' },
            take: 1000
        });

        if (products.length > 0) {
            content += `\n## Full Product Index\n\n`;
            products.forEach(product => {
                const url = `${baseUrl}${getLocalePath(`/product/${product.slug}`, product.lang as any)}`;
                content += `- [${product.name}](${url}): ${stripHtml(product.description)} (${product.lang})\n`;
            });
        }

        // 4. 其他资源
        content += `\n## Other Resources\n\n`;
        content += `- [Summary Index](${baseUrl}/llms.txt): A concise summary of the site.\n`;
        content += `- [XML Sitemap](${baseUrl}/sitemap.xml): Machine-readable URL list.\n`;

        content += `\n---\n*Generated by Molicms for AI Interoperability. Full dynamic index. Last updated: ${new Date().toISOString().split('T')[0]}.*`;

        return new Response(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=60',
            },
        });
    } catch (error) {
        console.error('Error generating llms-full.txt:', error);
        return new Response('Error generating llms-full.txt', { status: 500 });
    }
}
