
export interface FontOption {
    name: string;
    value: string;
    category?: string;
}

export const FONT_FAMILIES: FontOption[] = [
    // --- 中文字体 (Chinese) ---
    { name: '默认 (Default)', value: 'sans-serif' },
    { name: '宋体 (SimSun)', value: 'SimSun, STSong, sans-serif' },
    { name: '黑体 (SimHei)', value: 'SimHei, STHeiti, sans-serif' },
    { name: '微软雅黑 (YaHei)', value: '"Microsoft YaHei", "PingFang SC", sans-serif' },
    { name: '楷体 (KaiTi)', value: 'KaiTi, STKaiti, sans-serif' },
    { name: '仿宋 (FangSong)', value: 'FangSong, STFangsong, sans-serif' },
    { name: '隶书 (LiSu)', value: 'LiSu, STLiti, sans-serif' },
    { name: '幼圆 (YouYuan)', value: 'YouYuan, sans-serif' },
    { name: '华文细黑', value: 'STXihei, sans-serif' },
    { name: '华文楷体', value: 'STKaiti, sans-serif' },
    { name: '华文宋体', value: 'STSong, sans-serif' },
    { name: '华文仿宋', value: 'STFangsong, sans-serif' },
    { name: '华文中宋', value: 'STZhongsong, sans-serif' },
    { name: '华文琥珀', value: 'STHupo, sans-serif' },
    { name: '华文新魏', value: 'STXinwei, sans-serif' },
    { name: '华文隶书', value: 'STLiti, sans-serif' },
    { name: '华文行楷', value: 'STXingkai, sans-serif' },
    { name: '冬青黑体 (Hiragino)', value: '"Hiragino Sans GB", sans-serif' },
    { name: '兰亭黑 (Lantinghei)', value: '"Lantinghei SC", sans-serif' },
    { name: '方正舒体', value: 'FZShuTi, sans-serif' },
    { name: '方正姚体', value: 'FZYaoti, sans-serif' },

    // --- 通用西文 (General Western) ---
    { name: 'Arial', value: 'Arial, Helvetica, sans-serif' },
    { name: 'Arial Black', value: '"Arial Black", Gadget, sans-serif' },
    { name: 'Arial Narrow', value: '"Arial Narrow", sans-serif' },
    { name: 'Arial Rounded', value: '"Arial Rounded MT Bold", sans-serif' },
    { name: 'Times New Roman', value: '"Times New Roman", Times, serif' },
    { name: 'Courier New', value: '"Courier New", Courier, monospace' },
    { name: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
    { name: 'Georgia', value: 'Georgia, serif' },
    { name: 'Tahoma', value: 'Tahoma, Geneva, sans-serif' },
    { name: 'Trebuchet MS', value: '"Trebuchet MS", Helvetica, sans-serif' },
    { name: 'Impact', value: 'Impact, Charcoal, sans-serif' },
    { name: 'Comic Sans MS', value: '"Comic Sans MS", cursive, sans-serif' },
    { name: 'Lucida Sans', value: '"Lucida Sans Unicode", "Lucida Grande", sans-serif' },
    { name: 'Lucida Console', value: '"Lucida Console", Monaco, monospace' },
    { name: 'Palatino', value: '"Palatino Linotype", "Book Antiqua", Palatino, serif' },
    { name: 'Garamond', value: 'Garamond, serif' },
    { name: 'Bookman', value: '"Bookman Old Style", serif' },
    { name: 'Avant Garde', value: '"Avant Garde", sans-serif' },

    // --- Google Fonts / Web Fonts (Sans-serif) ---
    { name: 'Roboto', value: 'Roboto, sans-serif' },
    { name: 'Open Sans', value: '"Open Sans", sans-serif' },
    { name: 'Lato', value: 'Lato, sans-serif' },
    { name: 'Montserrat', value: 'Montserrat, sans-serif' },
    { name: 'Oswald', value: 'Oswald, sans-serif' },
    { name: 'Source Sans Pro', value: '"Source Sans Pro", sans-serif' },
    { name: 'Slabo 27px', value: '"Slabo 27px", serif' },
    { name: 'Raleway', value: 'Raleway, sans-serif' },
    { name: 'PT Sans', value: '"PT Sans", sans-serif' },
    { name: 'Merriweather', value: 'Merriweather, serif' },
    { name: 'Noto Sans', value: '"Noto Sans", sans-serif' },
    { name: 'Nunito', value: 'Nunito, sans-serif' },
    { name: 'Concert One', value: '"Concert One", sans-serif' },
    { name: 'Prompt', value: 'Prompt, sans-serif' },
    { name: 'Work Sans', value: '"Work Sans", sans-serif' },
    { name: 'Quicksand', value: 'Quicksand, sans-serif' },
    { name: 'Rubik', value: 'Rubik, sans-serif' },
    { name: 'Karla', value: 'Karla, sans-serif' },
    { name: 'Fira Sans', value: '"Fira Sans", sans-serif' },
    { name: 'Hind', value: 'Hind, sans-serif' },
    { name: 'Arimo', value: 'Arimo, sans-serif' },
    { name: 'PT Sans Narrow', value: '"PT Sans Narrow", sans-serif' },
    { name: 'Inconsolata', value: 'Inconsolata, monospace' },
    { name: 'Bitter', value: 'Bitter, serif' },
    { name: 'Dosis', value: 'Dosis, sans-serif' },
    { name: 'Oxygen', value: 'Oxygen, sans-serif' },
    { name: 'Cabin', value: 'Cabin, sans-serif' },
    { name: 'Ubuntu', value: 'Ubuntu, sans-serif' },
    { name: 'Lobster', value: 'Lobster, cursive' },
    { name: 'Pacifico', value: 'Pacifico, cursive' },
    { name: 'Shadows Into Light', value: '"Shadows Into Light", cursive' },
    { name: 'Dancing Script', value: '"Dancing Script", cursive' },
    { name: 'Amatic SC', value: '"Amatic SC", cursive' },
    { name: 'Bree Serif', value: '"Bree Serif", serif' },
    { name: 'Anton', value: 'Anton, sans-serif' },
    { name: 'Muli', value: 'Muli, sans-serif' },
    { name: 'Titillium Web', value: '"Titillium Web", sans-serif' },
    { name: 'Varela Round', value: '"Varela Round", sans-serif' },
    { name: 'Crimson Text', value: '"Crimson Text", serif' },
    { name: 'Playfair Display', value: '"Playfair Display", serif' },
    { name: 'Indie Flower', value: '"Indie Flower", cursive' },
    { name: 'Maven Pro', value: '"Maven Pro", sans-serif' },
    { name: 'Poiret One', value: '"Poiret One", cursive' },
    { name: 'Rokkitt', value: 'Rokkitt, serif' },
    { name: 'Righteous', value: 'Righteous, cursive' },
    { name: 'Fredoka One', value: '"Fredoka One", cursive' },
    { name: 'Abril Fatface', value: '"Abril Fatface", cursive' },
    { name: 'Signika', value: 'Signika, sans-serif' },
    { name: 'Inconsolata', value: 'Inconsolata, monospace' },
    { name: 'Josefin Sans', value: '"Josefin Sans", sans-serif' },
    { name: 'Libre Baskerville', value: '"Libre Baskerville", serif' },
    { name: 'Permanent Marker', value: '"Permanent Marker", cursive' },
    { name: 'Crete Round', value: '"Crete Round", serif' },
    { name: 'Patrick Hand', value: '"Patrick Hand", cursive' },
    { name: 'Cookie', value: 'Cookie, cursive' },
    { name: 'Satisfy', value: 'Satisfy, cursive' },
    { name: 'Great Vibes', value: '"Great Vibes", cursive' },
    { name: 'Kaushan Script', value: '"Kaushan Script", cursive' },
    { name: 'Sacramento', value: 'Sacramento, cursive' },
    { name: 'Orbitron', value: 'Orbitron, sans-serif' },
    { name: 'Cinzel', value: 'Cinzel, serif' },
    { name: 'Parisienne', value: 'Parisienne, cursive' },
    { name: 'Handlee', value: 'Handlee, cursive' },
    { name: 'Courgette', value: 'Courgette, cursive' },
    { name: 'Bangers', value: 'Bangers, cursive' },
    { name: 'Gloria Hallelujah', value: '"Gloria Hallelujah", cursive' },
    { name: 'Tangerine', value: 'Tangerine, cursive' },
    { name: 'Monoton', value: 'Monoton, cursive' },
    { name: 'Press Start 2P', value: '"Press Start 2P", cursive' },
    { name: 'Audiowide', value: 'Audiowide, cursive' },
    { name: 'Gruppo', value: 'Gruppo, cursive' },
    { name: 'Coming Soon', value: '"Coming Soon", cursive' },
    { name: 'Covered By Your Grace', value: '"Covered By Your Grace", cursive' },
    { name: 'Homemade Apple', value: '"Homemade Apple", cursive' },
    { name: 'Kalam', value: 'Kalam, cursive' },
    { name: 'Nothing You Could Do', value: '"Nothing You Could Do", cursive' },
    { name: 'Pangolin', value: 'Pangolin, cursive' },
    { name: 'Rock Salt', value: '"Rock Salt", cursive' },
    { name: 'Shadows Into Light Two', value: '"Shadows Into Light Two", cursive' },
    { name: 'Syncopate', value: 'Syncopate, sans-serif' },
    { name: 'Yellowtail', value: 'Yellowtail, cursive' },
    { name: 'Aclonica', value: 'Aclonica, sans-serif' },
    { name: 'Acme', value: 'Acme, sans-serif' },
    { name: 'Actor', value: 'Actor, sans-serif' },
    { name: 'Adamina', value: 'Adamina, serif' },
    { name: 'Advent Pro', value: '"Advent Pro", sans-serif' },
    { name: 'Aguafina Script', value: '"Aguafina Script", cursive' },
    { name: 'Akronim', value: 'Akronim, cursive' },
    { name: 'Aladin', value: 'Aladin, cursive' },
    { name: 'Aldrich', value: 'Aldrich, sans-serif' },
    { name: 'Alef', value: 'Alef, sans-serif' },
    { name: 'Alegreya', value: 'Alegreya, serif' },
    { name: 'Alegreya SC', value: '"Alegreya SC", serif' },
    { name: 'Alegreya Sans', value: '"Alegreya Sans", sans-serif' },
    { name: 'Alegreya Sans SC', value: '"Alegreya Sans SC", sans-serif' },
    { name: 'Alex Brush', value: '"Alex Brush", cursive' },
    { name: 'Alfa Slab One', value: '"Alfa Slab One", cursive' },
    { name: 'Alice', value: 'Alice, serif' },
    { name: 'Alike', value: 'Alike, serif' },
    { name: 'Alike Angular', value: '"Alike Angular", serif' },
    { name: 'Allan', value: 'Allan, cursive' },
    { name: 'Allerta', value: 'Allerta, sans-serif' },
    { name: 'Allerta Stencil', value: '"Allerta Stencil", sans-serif' },
    { name: 'Allura', value: 'Allura, cursive' },
    { name: 'Almendra', value: 'Almendra, serif' },
    { name: 'Almendra Display', value: '"Almendra Display", serif' },
    { name: 'Almendra SC', value: '"Almendra SC", serif' },
    { name: 'Amarante', value: 'Amarante, cursive' },
    { name: 'Amaranth', value: 'Amaranth, sans-serif' },
    { name: 'Amethysta', value: 'Amethysta, serif' },
    { name: 'Anaheim', value: 'Anaheim, sans-serif' },
    { name: 'Andada', value: 'Andada, serif' },
    { name: 'Andika', value: 'Andika, sans-serif' },
    { name: 'Angkor', value: 'Angkor, cursive' },
    { name: 'Annie Use Your Telescope', value: '"Annie Use Your Telescope", cursive' },
    { name: 'Anonymous Pro', value: '"Anonymous Pro", monospace' },
    { name: 'Antic', value: 'Antic, sans-serif' },
    { name: 'Antic Didone', value: '"Antic Didone", serif' },
    { name: 'Antic Slab', value: '"Antic Slab", serif' },
    { name: 'Arapey', value: 'Arapey, serif' },
    { name: 'Arbutus', value: 'Arbutus, cursive' },
    { name: 'Arbutus Slab', value: '"Arbutus Slab", serif' },
    { name: 'Architects Daughter', value: '"Architects Daughter", cursive' },
    { name: 'Archivo Black', value: '"Archivo Black", sans-serif' },
    { name: 'Archivo Narrow', value: '"Archivo Narrow", sans-serif' },
    { name: 'Arvo', value: 'Arvo, serif' },
    { name: 'Asap', value: 'Asap, sans-serif' },
    { name: 'Asset', value: 'Asset, cursive' },
    { name: 'Astloch', value: 'Astloch, cursive' },
    { name: 'Asul', value: 'Asul, sans-serif' },
    { name: 'Atomic Age', value: '"Atomic Age", cursive' },
    { name: 'Aubrey', value: 'Aubrey, cursive' },
    { name: 'Autour One', value: '"Autour One", cursive' },
    { name: 'Average', value: 'Average, serif' },
    { name: 'Average Sans', value: '"Average Sans", sans-serif' },
    { name: 'Averia Gruesa Libre', value: '"Averia Gruesa Libre", cursive' },
    { name: 'Averia Libre', value: '"Averia Libre", cursive' },
    { name: 'Averia Sans Libre', value: '"Averia Sans Libre", cursive' },
    { name: 'Averia Serif Libre', value: '"Averia Serif Libre", cursive' },
    { name: 'Bad Script', value: '"Bad Script", cursive' },
    { name: 'Balthazar', value: 'Balthazar, serif' },
    { name: 'Baumans', value: 'Baumans, cursive' },
    { name: 'Bayon', value: 'Bayon, cursive' },
    { name: 'Belgrano', value: 'Belgrano, serif' },
    { name: 'Belleza', value: 'Belleza, sans-serif' },
    { name: 'BenchNine', value: 'BenchNine, sans-serif' },
    { name: 'Bentham', value: 'Bentham, serif' },
    { name: 'Berkshire Swash', value: '"Berkshire Swash", cursive' },
    { name: 'Bevan', value: 'Bevan, cursive' },
    { name: 'Bigelow Rules', value: '"Bigelow Rules", cursive' },
    { name: 'Bigshot One', value: '"Bigshot One", cursive' },
    { name: 'Bilbo', value: 'Bilbo, cursive' },
    { name: 'Bilbo Swash Caps', value: '"Bilbo Swash Caps", cursive' },
    { name: 'Black Ops One', value: '"Black Ops One", cursive' },
    { name: 'Bokor', value: 'Bokor, cursive' },
    { name: 'Bonbon', value: 'Bonbon, cursive' },
    { name: 'Boogaloo', value: 'Boogaloo, cursive' },
    { name: 'Bowlby One', value: '"Bowlby One", cursive' },
    { name: 'Bowlby One SC', value: '"Bowlby One SC", cursive' },
    { name: 'Brawler', value: 'Brawler, serif' },
    { name: 'Bree Serif', value: '"Bree Serif", serif' },
    { name: 'Bubblegum Sans', value: '"Bubblegum Sans", cursive' },
    { name: 'Bubbler One', value: '"Bubbler One", sans-serif' },
    { name: 'Buda', value: 'Buda, cursive' },
    { name: 'Buenard', value: 'Buenard, serif' },
    { name: 'Butcherman', value: 'Butcherman, cursive' },
    { name: 'Butterfly Kids', value: '"Butterfly Kids", cursive' },
    { name: 'Cabin Condensed', value: '"Cabin Condensed", sans-serif' },
    { name: 'Cabin Sketch', value: '"Cabin Sketch", cursive' },
    { name: 'Caesar Dressing', value: '"Caesar Dressing", cursive' },
    { name: 'Cagliostro', value: 'Cagliostro, sans-serif' },
    { name: 'Calligraffitti', value: 'Calligraffitti, cursive' },
    { name: 'Cambo', value: 'Cambo, serif' },
    { name: 'Candal', value: 'Candal, sans-serif' },
    { name: 'Cantarell', value: 'Cantarell, sans-serif' },
    { name: 'Cantata One', value: '"Cantata One", serif' },
    { name: 'Cantora One', value: '"Cantora One", sans-serif' },
    { name: 'Capriola', value: 'Capriola, sans-serif' },
    { name: 'Cardo', value: 'Cardo, serif' },
    { name: 'Carme', value: 'Carme, sans-serif' },
    { name: 'Carrois Gothic', value: '"Carrois Gothic", sans-serif' },
    { name: 'Carrois Gothic SC', value: '"Carrois Gothic SC", sans-serif' },
    { name: 'Carter One', value: '"Carter One", cursive' },
    { name: 'Caudex', value: 'Caudex, serif' },
    { name: 'Cedarville Cursive', value: '"Cedarville Cursive", cursive' },
    { name: 'Ceviche One', value: '"Ceviche One", cursive' },
    { name: 'Changa One', value: '"Changa One", cursive' },
    { name: 'Chango', value: 'Chango, cursive' },
    { name: 'Chau Philomene One', value: '"Chau Philomene One", sans-serif' },
    { name: 'Chela One', value: '"Chela One", cursive' },
    { name: 'Chelsea Market', value: '"Chelsea Market", cursive' },
    { name: 'Chenla', value: 'Chenla, cursive' },
    { name: 'Cherry Cream Soda', value: '"Cherry Cream Soda", cursive' },
    { name: 'Cherry Swash', value: '"Cherry Swash", cursive' },
    { name: 'Chewy', value: 'Chewy, cursive' },
    { name: 'Chicle', value: 'Chicle, cursive' },
    { name: 'Chivo', value: 'Chivo, sans-serif' },
    { name: 'Cinzel Decorative', value: '"Cinzel Decorative", cursive' },
    { name: 'Clicker Script', value: '"Clicker Script", cursive' },
    { name: 'Coda', value: 'Coda, cursive' },
    { name: 'Coda Caption', value: '"Coda Caption", sans-serif' },
    { name: 'Codystar', value: 'Codystar, cursive' },
    { name: 'Combo', value: 'Combo, cursive' },
    { name: 'Comfortaa', value: 'Comfortaa, cursive' },
    { name: 'Contrail One', value: '"Contrail One", cursive' },
    { name: 'Convergence', value: 'Convergence, sans-serif' },
    { name: 'Cookie', value: 'Cookie, cursive' },
    { name: 'Copse', value: 'Copse, serif' },
    { name: 'Corben', value: 'Corben, cursive' },
    { name: 'Cousine', value: 'Cousine, monospace' },
    { name: 'Coustard', value: 'Coustard, serif' },
    { name: 'Covered By Your Grace', value: '"Covered By Your Grace", cursive' },
    { name: 'Crafty Girls', value: '"Crafty Girls", cursive' },
    { name: 'Creepster', value: 'Creepster, cursive' },
    { name: 'Crete Round', value: '"Crete Round", serif' },
    { name: 'Crimson Text', value: '"Crimson Text", serif' },
    { name: 'Croissant One', value: '"Croissant One", cursive' },
    { name: 'Crushed', value: 'Crushed, cursive' },
    { name: 'Cuprum', value: 'Cuprum, sans-serif' },
    { name: 'Cutive', value: 'Cutive, serif' },
    { name: 'Cutive Mono', value: '"Cutive Mono", monospace' },
    { name: 'Damion', value: 'Damion, cursive' },
    { name: 'Dancing Script', value: '"Dancing Script", cursive' },
    { name: 'Dangrek', value: 'Dangrek, cursive' },
    { name: 'Dawning of a New Day', value: '"Dawning of a New Day", cursive' },
    { name: 'Days One', value: '"Days One", sans-serif' },
    { name: 'Delius', value: 'Delius, cursive' },
    { name: 'Delius Swash Caps', value: '"Delius Swash Caps", cursive' },
    { name: 'Delius Unicase', value: '"Delius Unicase", cursive' },
    { name: 'Della Respira', value: '"Della Respira", serif' },
    { name: 'Denk One', value: '"Denk One", sans-serif' },
    { name: 'Devonshire', value: 'Devonshire, cursive' },
    { name: 'Didact Gothic', value: '"Didact Gothic", sans-serif' },
    { name: 'Diplomata', value: 'Diplomata, cursive' },
    { name: 'Diplomata SC', value: '"Diplomata SC", cursive' },
    { name: 'Domine', value: 'Domine, serif' },
    { name: 'Donegal One', value: '"Donegal One", serif' },
    { name: 'Doppio One', value: '"Doppio One", sans-serif' },
    { name: 'Dorsa', value: 'Dorsa, sans-serif' },
    { name: 'Dosis', value: 'Dosis, sans-serif' },
    { name: 'Dr Sugiyama', value: '"Dr Sugiyama", cursive' },
    { name: 'Droid Sans', value: '"Droid Sans", sans-serif' },
    { name: 'Droid Sans Mono', value: '"Droid Sans Mono", monospace' },
    { name: 'Droid Serif', value: '"Droid Serif", serif' },
    { name: 'Duru Sans', value: '"Duru Sans", sans-serif' },
    { name: 'Dynalight', value: 'Dynalight, cursive' },
    { name: 'Eagle Lake', value: '"Eagle Lake", cursive' },
    { name: 'Eater', value: 'Eater, cursive' },
    { name: 'EB Garamond', value: '"EB Garamond", serif' },
    { name: 'Economica', value: 'Economica, sans-serif' },
    { name: 'Electrolize', value: 'Electrolize, sans-serif' },
    { name: 'Elsie', value: 'Elsie, cursive' },
    { name: 'Elsie Swash Caps', value: '"Elsie Swash Caps", cursive' },
    { name: 'Emblema One', value: '"Emblema One", cursive' },
    { name: 'Emilys Candy', value: '"Emilys Candy", cursive' },
    { name: 'Engagement', value: 'Engagement, cursive' },
    { name: 'Englebert', value: 'Englebert, cursive' },
    { name: 'Eniqua', value: 'Eniqua, serif' },
    { name: 'Erica One', value: '"Erica One", cursive' },
    { name: 'Esteban', value: 'Esteban, serif' },
    { name: 'Euphoria Script', value: '"Euphoria Script", cursive' },
    { name: 'Ewert', value: 'Ewert, cursive' },
    { name: 'Exo', value: 'Exo, sans-serif' },
    { name: 'Exo 2', value: '"Exo 2", sans-serif' },
    { name: 'Expletus Sans', value: '"Expletus Sans", cursive' },
    { name: 'Fanwood Text', value: '"Fanwood Text", serif' },
    { name: 'Fascinate', value: 'Fascinate, cursive' },
    { name: 'Fascinate Inline', value: '"Fascinate Inline", cursive' },
    { name: 'Faster One', value: '"Faster One", cursive' },
    { name: 'Fasthand', value: 'Fasthand, serif' },
    { name: 'Fauna One', value: '"Fauna One", serif' },
    { name: 'Federant', value: 'Federant, cursive' },
    { name: 'Federo', value: 'Federo, sans-serif' },
    { name: 'Felipa', value: 'Felipa, cursive' },
    { name: 'Fenix', value: 'Fenix, serif' },
    { name: 'Finger Paint', value: '"Finger Paint", cursive' },
    { name: 'Fjalla One', value: '"Fjalla One", sans-serif' },
    { name: 'Fjord One', value: '"Fjord One", serif' },
    { name: 'Flamenco', value: 'Flamenco, cursive' },
    { name: 'Flavors', value: 'Flavors, cursive' },
    { name: 'Fondamento', value: 'Fondamento, cursive' },
    { name: 'Fontdiner Swanky', value: '"Fontdiner Swanky", cursive' },
    { name: 'Forum', value: 'Forum, cursive' },
    { name: 'Francois One', value: '"Francois One", sans-serif' },
    { name: 'Freckle Face', value: '"Freckle Face", cursive' },
    { name: 'Fredericka the Great', value: '"Fredericka the Great", cursive' },
];
